clear all
close all

% Find P(HHUUHHUUHHUU)

observation = [1 1 0 1 1 0];
length = length(observation);

p = [.4; ...
     .3; ...
     .3];
e = [.9,.1; ...
     .5,.5; ...
     .2,.8];
t = [.7,.2,.1; ...
     .3,.4,.3; ...
     .1,.2,.7];

% p = [.7; ...
%      .2; ...
%      .1];
% e = [.9,.1; ...
%      .5,.5; ...
%      .2,.8];
% t = [.7,.2,.1; ...
%      .5,.3,.2; ...
%      .3,.3,.4];  
 
alpha = zeros(length,3);

% Innitial Alpha
if observation(1) == 1 %Happy
    alpha(1,1) = p(1)*e(1,1);
    alpha(1,2) = p(2)*e(2,1);
    alpha(1,3) = p(3)*e(3,1);
else
    alpha(1,1) = p(1)*e(1,2);
    alpha(1,2) = p(2)*e(2,2);
    alpha(1,3) = p(3)*e(3,2);
end
    
iter = 1;
for i = observation
    if iter == 1
        iter = iter+1;
    else
        if i == 1 % Happy
        alpha(iter,1) = (alpha(iter-1,1)*t(1,1) + ...
                         alpha(iter-1,2)*t(2,1) + ...
                         alpha(iter-1,3)*t(3,1)) * e(1,1);
        alpha(iter,2) = (alpha(iter-1,1)*t(1,2) + ...
                         alpha(iter-1,2)*t(2,2) + ...
                         alpha(iter-1,3)*t(3,2)) * e(2,1);
        alpha(iter,3) = (alpha(iter-1,1)*t(1,3) + ...
                         alpha(iter-1,2)*t(2,3) + ...
                         alpha(iter-1,3)*t(3,3)) * e(3,1);
        else
        alpha(iter,1) = (alpha(iter-1,1)*t(1,1) + ...
                         alpha(iter-1,2)*t(2,1) + ...
                         alpha(iter-1,3)*t(3,1)) * e(1,2);
        alpha(iter,2) = (alpha(iter-1,1)*t(1,2) + ...
                         alpha(iter-1,2)*t(2,2) + ...
                         alpha(iter-1,3)*t(3,2)) * e(2,2);
        alpha(iter,3) = (alpha(iter-1,1)*t(1,3) + ...
                         alpha(iter-1,2)*t(2,3) + ...
                         alpha(iter-1,3)*t(3,3)) * e(3,2);
        end
        iter = iter+1;
    end
end